---
- name: Export AWX Job Templates
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Export a job template named "My Template"
      awx.awx.export:
        job_templates: "kickstart-switches"
        # Define connection details, e.g.,
        controller_host: http://10.48.112.47:8082
        controller_username: admin
        controller_password: password
        verify_ssl: false # Adjust as needed
      register: export_output

    - name: Save export to a file
      copy:
        content: "{{ export_output['assets'] | to_nice_yaml }}"
        dest: "/var/lib/awx/projects/switch_export.yaml"
