- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
      ansible.builtin.debug:
        msg: "--- Starting configuration for node and switches"

