- name: Clear pending storage configuration
  uri:
    url: "{{ bmc_storage_url }}/{{ controller_name }}/Actions/Oem/DellStorageController.ClearPending"
    method: POST
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
    body_format: json
    body: {}
    status_code: [200, 202, 204]
  delegate_to: "{{ bmc_delegate_host }}"
