# Create RAID volume

- set_fact:
    has_configure_jobs: false

- name: Extract drive URLs (alternative method)
  set_fact:
    drive_urls: "{{ m2_storage.json.Drives | json_query('[*].\"@odata.id\"') }}"
  when: m2_storage.json.Drives is defined

- name: Convert drive URLs to Redfish object array
  set_fact:
    drives: "{{ drive_urls | map('community.general.dict_kv', '@odata.id') | list }}"

- name: Check existing RAID Configuration Job
  include_tasks: check_raid_config_job.yml

- name: Create RAID volume
  uri:
    url: "{{ bmc_storage_url}}/{{ controller_name }}/Volumes"
    method: POST
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
    body_format: json
    body:
      RAIDType: "{{ raid_config.raid_level | upper }}"
      Drives: "{{ drives }}"
    status_code: [200, 201, 202, 204]
  register: volume_create
  delegate_to: "{{ bmc_delegate_host }}"
  retries: "{{ max_retries }}"
  delay: "{{ retry_delay }}"
  until: volume_create.status in [200, 201, 202, 204]
  when: not has_configure_jobs

- name: Wait for creation of RAID volume
  pause:
    seconds: 30

- name: Check existing RAID Configuration Job
  include_tasks: check_raid_config_job.yml

- name: Create raid configuration job
  include_tasks: create_raid_config_job.yml

- name: Retrieve current boot override settings
  uri:
    url: "{{ bmc_systems_url }}"
    method: GET
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
  register: current_boot
  delegate_to: "{{ bmc_delegate_host }}"

- name: Set next boot to UEFI Setup (one-time)
  uri:
    url: "{{ bmc_systems_url }}"
    method: PATCH
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
    body_format: json
    body:
      Boot:
        BootSourceOverrideTarget: BiosSetup
        BootSourceOverrideEnabled: Once
    status_code: [200, 204]
  register: uefi_result
  delegate_to: "{{ bmc_delegate_host }}"
  when: >
    current_boot.json.Boot.BootSourceOverrideTarget != "BiosSetup" or
    current_boot.json.Boot.BootSourceOverrideEnabled != "Once"

- name: Reboot system and wait 
  include_tasks: wait_for_system_up.yml

- name: Wait until RAID configure jobs to complete
  include_tasks: wait_for_raid_config_job.yml

- name: Wait for volume to appear
  uri:
    url: "{{ bmc_storage_url }}/{{ controller_name }}/Volumes"
    method: GET
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
  register: volumes_verify
  delegate_to: "{{ bmc_delegate_host }}"
  until: volumes_verify.json.Members | length > 0
  retries: "{{ raid_config.raid_config_retry }}"
  delay: "{{ raid_config.raid_config_delay }}"
  
- name: Volume creation completed
  debug:
    msg: "RAID volume created successfully"
