
  # Create raid config job
- name: Create raid configuration job
  shell: >
    sshpass -p '{{ bmc_password }}'
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    {{ hostvars[inventory_hostname].bmc_user }}@{{ hostvars[inventory_hostname].ipv6ULA }}
    "jobqueue create {{ controller_name }} -s TIME_NOW -r forced"
  register: raid_config_result
  delegate_to: "{{ bmc_delegate_host }}"
  when:
    - bmc_config.requires_job_cleanup is defined
    - bmc_config.requires_job_cleanup | bool
