---
# Delete a single volume with retry logic

- name: Attempt to delete Dell virtual volume 
  uri:
    url: "https://{{ bmc_ip }}{{ volume_uri }}"
    method: DELETE
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
    status_code: [200, 202, 204]
  register: delete_volume_result
  delegate_to: "{{ bmc_delegate_host }}"
  retries: 1
  delay: 10
  until: delete_volume_result.status in [200, 202, 204]
  failed_when: false

- debug:
    msg: "{{ delete_volume_result }}"

- name: Clear pending storage configuration
  shell: >
    sshpass -p '{{ bmc_password }}'
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    {{ hostvars[inventory_hostname].bmc_user }}@{{ hostvars[inventory_hostname].ipv6ULA }}
    "clearpending {{ controller_name }}"
  register: racadm_pending_result
  delegate_to: "{{ bmc_delegate_host }}"
  when: delete_volume_result.status not in [200, 202, 204]

- debug:
    msg: "{{ racadm_pending_result }}"
    
- name: Wait for clearing pending storage configuration
  pause:
    seconds: 30

# Retrying volume deletion now

- name: Delete volume using CLI
  shell: >
    sshpass -p '{{ bmc_password }}'
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    {{ hostvars[inventory_hostname].bmc_user }}@{{ hostvars[inventory_hostname].ipv6ULA }}
    "storage deletevd:Disk.Virtual.0:{{ controller_name }}"
  register: racadm_delete_result
  delegate_to: "{{ bmc_delegate_host }}"
  when: delete_volume_result.status not in [200, 202, 204]

- debug:
    msg: "{{ racadm_delete_result }}"
