
# roles/configure_raid/tasks/main.yml

- name: Retrieve credentials for server
  include_role:
    name: common
    tasks_from: cred.yml
  vars:
    credential_server_name: "{{OCPRole}}-secret"
    credential_userid: "USERID"

- name: Map kickstart.json variables to task variables
  ansible.builtin.set_fact:
    # BMC credentials from users array
    bmc_user: "{{ credential_username }}"
    bmc_password: "{{ credential_password | b64decode }}"
    
- name: Discover configuration
  include_tasks: discover.yml
  
- name: Check Power State
  include_tasks: manage_power.yml

- name: Validate Storage Controller
  include_tasks: validate_controller.yml

- name: Validate disks
  include_tasks: validate_disks.yml

- name: Validate volume
  include_tasks: validate_volumes.yml
  
- name: Delete volume
  include_tasks: delete_volumes.yml

- name: Create volume
  include_tasks: create_volume.yml
