- name: Get all jobs
  uri:
    url: "{{ bmc_manager_url }}/Jobs"
    method: GET
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
  register: jobs_list
  delegate_to: "{{ bmc_delegate_host }}"

- name: Get job details
  uri:
    url: "{{ bmc_base_url }}{{ item['@odata.id'] }}"
    method: GET
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
  loop: "{{ jobs_list.json.Members | default([]) }}"
  register: job_details_check
  delegate_to: "{{ bmc_delegate_host }}"

- name: Set active job flag
  set_fact:
    configure_jobs_active: >-
      {{
        job_details_check.results | default([])
        | map(attribute='json')
        | selectattr('JobState', 'in', ['Pending','Running','New','Scheduled'])
        | selectattr('Name', 'defined')
        | selectattr('Name', 'match', '^Configure:')
        | list
        | length > 0
      }}
