

- name: Restart Server
  uri:
    url: "{{ bmc_reset_url }}"
    method: POST
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
    body_format: json
    body:
      ResetType: "ForceRestart"
    status_code: [200, 204]
  delegate_to: "{{ bmc_delegate_host }}"
    
- name: Wait for system to reach setup state
  uri:
    url: "{{ bmc_systems_url }}"
    method: GET
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
    return_content: yes
    status_code: [200]
  register: power_state_check
  delegate_to: "{{ bmc_delegate_host }}"
  retries: "{{ max_retries }}"
  delay: "{{ delay_power_on }}"
  until: >
    power_state_check.json.PowerState is defined and
    power_state_check.json.PowerState == "On"

- name: Wait for storage controller discovery
  uri:
    url: "{{ bmc_storage_url }}"
    method: GET
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: no
  register: storage_list
  retries: "{{ max_retries }}"
  delay: "{{ delay_power_on }}"
  until:
    - storage_list.status == 200
    - storage_list.json.Members | length > 0
  delegate_to: "{{ bmc_delegate_host }}"
