
- name: Set bmc lla interface
  set_fact:
    bmc_lla_interface: "eno2"

- name: Wait for BMC SSH to become reachable
  shell: |
    nc -z -6 {{ ipv6LLA }}%{{ bmc_lla_interface }} 22
  register: ssh_check
  retries: 60
  delay: 10
  until: ssh_check.rc == 0
  delegate_to: jump-host

- name: Generate BMC secret
  set_fact:
    updated_bmc_password: >-
      {{
        lookup('password', '/dev/null length=20 chars=ascii_letters,digits') +
        '!'
      }}

- debug:
    msg: "updated_bmc_password = {{ updated_bmc_password }}"
    
- name: Configure BMC Account
  uri:
    url: "https://[{{ ipv6LLA }}%{{ bmc_lla_interface }}]/redfish/v1/AccountService/Accounts/1"
    method: PATCH
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    force_basic_auth: yes
    validate_certs: no
    body_format: json
    body:
      Password: "{{ updated_bmc_password }}"
    status_code: 200
  when: bmc_capabilities.require_patch_default_acct is defined  
  delegate_to: jump-host


- name: Generate BMC secret
  set_fact:
    bmc_password: "{{ updated_bmc_password }}"
