
- name: Ensure hvac Python library is installed
  ansible.builtin.pip:
    name: hvac
    state: present
    
- name: Extract and combine secrets from vault data
  ansible.builtin.set_fact:
    vault_secrets: "{{ (CNIMMSecret | default([])) + (SwitchSecret | default([])) }}"
 
- name: Display retrieved cnimm data
  debug:
    var: vault_secrets
  register: vault_result_cnimm
