---
# Define the computeNodeIntegratedManagementModules variable
- name: Set compute node integrated management modules data
  set_fact:
    computeNodeIntegratedManagementModules:
      - ipv6ULA: "fd8c:215d:178e:c0de:765d:22ff:fee4:2441"
        ipv6LLA: "fe80::765d:22ff:fee4:2441"
        serialNum: "JZ004CR9"
        mtm: "7D73CTO1WW"
        manufacturer: "Lenovo"
        ibmSerialNumber: "G2AUTO1-RU2"
        ibmMTM: "9155-C10"
        uuid: "5A006E0C441A11EFB336765D22E42443"
        type: "storage"
        OCPRole: "control-1-ru2"
        location: "RU2"
        nodeIndex: "1"
        name: "IMM_RU2"
        bootDevice: "/dev/disk/by-path/pci-0000:03:00.0-nvme-1"
        users:
          - user: "CEUSER"
            password: "dl9GajRHRVlVRVE="
            group: "Administrator"
            number: 2
          - user: "ISFUSER"
            password: "YjBvbTR6X1VoV0s="
            group: "Administrator"
            number: 3
          - user: "USERID"
            password: "YWhLWEdUcG9jMw=="
            group: "Administrator"
            number: 1
        pxeSlotLabel: "UEFI:   SLOT 1 (2A/0/0) PXE IPv4  Mellanox ConnectX-6 Lx 10/25GbE SFP28 2-port PCIe Ethernet Adapter - 58:A2:E1:54:84:CA"
        networkCards:
          - slot-1:
              - "58:a2:e1:54:84:ca"
              - "58:a2:e1:54:84:cb"
          - slot-3:
              - "a0:88:c2:a1:a4:4e"
              - "a0:88:c2:a1:a4:4f"
          - slot-6:
              - "6c:fe:54:92:1d:bc"
              - "6c:fe:54:92:1d:bd"
              - "6c:fe:54:92:1d:be"
              - "6c:fe:54:92:1d:bf"
        networkInterfaces:
          - macAddress: "58:a2:e1:54:84:ca"
            secondaryMacAddress: "58:a2:e1:54:84:cb"
            interfaceName: "bond1"
            interfaceLeg1: "ens1f0np0"
            interfaceLeg2: "ens1f1np1"
            interfaceType: "provisioning"
            interfaceMacList: null
          - macAddress: "a0:88:c2:a1:a4:4e"
            secondaryMacAddress: "a0:88:c2:a1:a4:4f"
            interfaceName: "bond0"
            interfaceLeg1: "ens3f0np0"
            interfaceLeg2: "ens3f1np1"
            interfaceType: "baremetal"
            interfaceMacList: null
        unusedInterfaces:
          - "ens6f0"
          - "ens6f1"
          - "ens6f2"
          - "ens6f3"
        nvme:
          - productName: "SAMSUNG MZWLO3T8HCLS-00A07"
            location: "Bay 0"
            slotNumber: "0"
            osDriveNameByPath: "/dev/disk/by-path/pci-0000:c0:00.0-nvme-1"
            serialNumber: "S794NC0X512322"
            capacity: "3.84TB"
            manufacture: "SAMSUNG"
          - productName: "SAMSUNG MZWLO3T8HCLS-00A07"
            location: "Bay 1"
            slotNumber: "1"
            osDriveNameByPath: "/dev/disk/by-path/pci-0000:bf:00.0-nvme-1"
            serialNumber: "S794NC0X512324"
            capacity: "3.84TB"
            manufacture: "SAMSUNG"
          - productName: "SAMSUNG MZWLO3T8HCLS-00A07"
            location: "Bay 2"
            slotNumber: "2"
            osDriveNameByPath: "/dev/disk/by-path/pci-0000:be:00.0-nvme-1"
            serialNumber: "S794NC0X300603"
            capacity: "3.84TB"
            manufacture: "SAMSUNG"
          - productName: "SAMSUNG MZWLO3T8HCLS-00A07"
            location: "Bay 3"
            slotNumber: "3"
            osDriveNameByPath: "/dev/disk/by-path/pci-0000:bd:00.0-nvme-1"
            serialNumber: "S794NC0X300534"
            capacity: "3.84TB"
            manufacture: "SAMSUNG"
          - productName: "SAMSUNG MZWLO3T8HCLS-00A07"
            location: "Bay 4"
            slotNumber: "4"
            osDriveNameByPath: "/dev/disk/by-path/pci-0000:d2:00.0-nvme-1"
            serialNumber: "S794NG0W700640"
            capacity: "3.84TB"
            manufacture: "SAMSUNG"
      - ipv6ULA: "fd8c:215d:178e:c0de:765d:22ff:fee4:1802"
        ipv6LLA: "fe80::765d:22ff:fee4:1802"
        serialNum: "JZ004CR8"
        mtm: "7D73CTO1WW"
        manufacturer: "Lenovo"
        ibmSerialNumber: "G2AUTO1-RU3"
        ibmMTM: "9155-C10"
        uuid: "AE22AACA443A11EFAA82765D22E41804"
        type: "storage"
        OCPRole: "control-1-ru3"
        location: "RU3"
        nodeIndex: "2"
        name: "IMM_RU3"
        bootDevice: "/dev/disk/by-path/pci-0000:03:00.0-nvme-1"
        users:
          - user: "USERID"
            password: "YWhLWEdUcG9jMw=="
            group: "Administrator"
            number: 1
          - user: "CEUSER"
            password: "dURmTmIzN0hackA="
            group: "Administrator"
            number: 2
          - user: "ISFUSER"
            password: "UUkyaTBAUElBTDA="
            group: "Administrator"
            number: 3
        pxeSlotLabel: "UEFI:   SLOT 1 (2A/0/0) PXE IPv4  Mellanox ConnectX-6 Lx 10/25GbE SFP28 2-port PCIe Ethernet Adapter - 58:A2:E1:54:88:E6"
        networkCards:
          - slot-1:
              - "58:a2:e1:54:88:e6"
              - "58:a2:e1:54:88:e7"
          - slot-3:
              - "a0:88:c2:a1:a8:2a"
              - "a0:88:c2:a1:a8:2b"
          - slot-6:
              - "6c:fe:54:99:f3:8a"
              - "6c:fe:54:99:f3:8b"
              - "6c:fe:54:99:f3:8c"
              - "6c:fe:54:99:f3:8d"
        networkInterfaces:
          - macAddress: "58:a2:e1:54:88:e6"
            secondaryMacAddress: "58:a2:e1:54:88:e7"
            interfaceName: "bond1"
            interfaceLeg1: "ens1f0np0"
            interfaceLeg2: "ens1f1np1"
            interfaceType: "provisioning"
            interfaceMacList: null
          - macAddress: "a0:88:c2:a1:a8:2a"
            secondaryMacAddress: "a0:88:c2:a1:a8:2b"
            interfaceName: "bond0"
            interfaceLeg1: "ens3f0np0"
            interfaceLeg2: "ens3f1np1"
            interfaceType: "baremetal"
            interfaceMacList: null
        unusedInterfaces:
          - "ens6f0"
          - "ens6f1"
          - "ens6f2"
          - "ens6f3"
        nvme:
          - productName: "SAMSUNG MZWLO3T8HCLS-00A07"
            location: "Bay 0"
            slotNumber: "0"
            osDriveNameByPath: "/dev/disk/by-path/pci-0000:c0:00.0-nvme-1"
            serialNumber: "S794NC0X512433"
            capacity: "3.84TB"
            manufacture: "SAMSUNG"
          - productName: "SAMSUNG MZWLO3T8HCLS-00A07"
            location: "Bay 1"
            slotNumber: "1"
            osDriveNameByPath: "/dev/disk/by-path/pci-0000:bf:00.0-nvme-1"
            serialNumber: "S794NC0X512370"
            capacity: "3.84TB"
            manufacture: "SAMSUNG"
          - productName: "SAMSUNG MZWLO3T8HCLS-00A07"
            location: "Bay 2"
            slotNumber: "2"
            osDriveNameByPath: "/dev/disk/by-path/pci-0000:be:00.0-nvme-1"
            serialNumber: "S794NC0X300374"
            capacity: "3.84TB"
            manufacture: "SAMSUNG"
          - productName: "SAMSUNG MZWLO3T8HCLS-00A07"
            location: "Bay 3"
            slotNumber: "3"
            osDriveNameByPath: "/dev/disk/by-path/pci-0000:bd:00.0-nvme-1"
            serialNumber: "S794NC0X300369"
            capacity: "3.84TB"
            manufacture: "SAMSUNG"
          - productName: "SAMSUNG MZWLO3T8HCLS-00A07"
            location: "Bay 4"
            slotNumber: "4"
            osDriveNameByPath: "/dev/disk/by-path/pci-0000:d2:00.0-nvme-1"
            serialNumber: "S794NC0X300396"
            capacity: "3.84TB"
            manufacture: "SAMSUNG"

# Example tasks demonstrating how to use the variable

- name: Display all compute nodes
  debug:
    msg: "Found {{ computeNodeIntegratedManagementModules | length }} compute nodes"

- name: Set vault credentials
  set_fact:
    vault_response:
      status: "Success"
      message: "Vault credentials retrieved successfully."
      messageCode: "INSTALL042"
      messageArgs: null
      errorMessage: ""
      data:
        CNIMMSecret:
          CNIMMSecret:
            - name: "control-1-ru2-secret"
              users:
                - group: "Administrator"
                  password: "qQ-03ywHJ26TejshriBhagwa"
                  user: "CEUSER"
                - group: "Administrator"
                  password: "GF4q9y9_CGQPrasadBhag"
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "PASSW0RD"
                  user: "USERID"
            - name: "control-1-ru3-secret"
              users:
                - group: "Administrator"
                  password: "iPFYxg@DDp8Bhagwa"
                  user: "CEUSER"
                - group: "Administrator"
                  password: "l@p1WBOs9NWTejshriBh"
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "PASSW0RD"
                  user: "USERID"
            - name: "control-1-ru4-secret"
              users:
                - group: "Administrator"
                  password: "E3dNoTO1_GdTejshriB"
                  user: "CEUSER"
                - group: "Administrator"
                  password: "2c9DM_8gzGgTejshriBhagwa"
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "PASSW0RDTejshriB"
                  user: "USERID"
            - name: "compute-1-ru5-secret"
              users:
                - group: "Administrator"
                  password: "GE4sVyIF0X_"
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "PASSW0RD"
                  user: "USERID"
                - group: "Administrator"
                  password: "nvLFnk_jUf8Fusionnnn12"
                  user: "CEUSER"
            - name: "compute-1-ru6-secret"
              users:
                - group: "Administrator"
                  password: "u6pOv8.Mb78Tejshri"
                  user: "CEUSER"
                - group: "Administrator"
                  password: "ySUlVD_2k17"
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "PASSW0RD"
                  user: "USERID"
            - name: "compute-1-ru7-secret"
              users:
                - group: "Administrator"
                  password: "Fe#6hdafdL9Prasad"
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "PASSW0RDBhalerao"
                  user: "USERID"
                - group: "Administrator"
                  password: "hdH00rNDK7#"
                  user: "CEUSER"
            - name: "servicenode-1-secret"
              users:
                - group: "Administrator"
                  password: "PASSW0RD"
                  user: "USERID"
                - group: "Administrator"
                  password: "CYRqU4#8lPqTejshr"
                  user: "CEUSER"
                - group: "Administrator"
                  password: "aaj530H3r@3"
                  user: "ISFUSER"
        ProvisionerPubPrivKeySecret:
          ProvisionerPubPrivKeySecret:
            - privateKey: |
                -----BEGIN OPENSSH PRIVATE KEY-----
                b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
                c2gtZWQyNTUxOQAAACBYdBB/WDQbZDwPUEwk00/zjkEPR5yfnPubgdX3tz7kIQAA
                AIhrHnpvax56bwAAAAtzc2gtZWQyNTUxOQAAACBYdBB/WDQbZDwPUEwk00/zjkEP
                R5yfnPubgdX3tz7kIQAAAEDSGO42NWO7VlCqXq35CO3umNi09RGCqi9D6feWPKCK
                Vlh0EH9YNBtkPA9QTCTTT/OOQQ9HnJ+c+5uB1fe3PuQhAAAAAAECAwQF
                -----END OPENSSH PRIVATE KEY-----
              publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFh0EH9YNBtkPA9QTCTTT/OOQQ9HnJ+c+5uB1fe3PuQh\n"
        SwitchSecret:
          SwitchSecret:
            - name: "hspeed1-f31l006-secret"
              snmpAuthPassword: "VsZbt3Nh89Tejsh"
              snmpPrivPassword: "kdLMuC237y"
              snmpUser: "ISFSNMPUSR"
              users:
                - group: "netedit"
                  password: "qJl@kjUs4o3Bhag"
                  user: "CEUSER"
                - group: "netedit"
                  password: "bMo1Ln9-Cl2"
                  user: "ISFUSER"
                - group: "admin"
                  password: "Abell4Cloud!"
                  user: "cumulus"
            - name: "hspeed2-f31l006-secret"
              snmpAuthPassword: "qD4fEpz71mTejshri"
              snmpPrivPassword: "3V4H2fmnlk"
              snmpUser: "ISFSNMPUSR"
              users:
                - group: "netedit"
                  password: "s4l5dQSUoV#"
                  user: "CEUSER"
                - group: "netedit"
                  password: "XEshz9tQ4E#"
                  user: "ISFUSER"
                - group: "admin"
                  password: "Abell4Cloud!"
                  user: "cumulus"
            - name: "mgmt1-f31l006-secret"
              snmpAuthPassword: "0Pi2jEBYQ9Tejshri"
              snmpPrivPassword: "Yhv4n5FTS2"
              snmpUser: "ISFSNMPUSR"
              users:
                - group: "netedit"
                  password: "E@ghjp7e0KU"
                  user: "CEUSER"
                - group: "netedit"
                  password: "OY0QHDh1dL$"
                  user: "ISFUSER"
                - group: "netedit"
                  password: "Abell4Cloud!"
                  user: "cumulus"
            - name: "mgmt2-f31l006-secret"
              snmpAuthPassword: "f5es9xQMj3fusioninstallTejshri"
              snmpPrivPassword: "N60cR9ruIa"
              snmpUser: "ISFSNMPUSR"
              users:
                - group: "netedit"
                  password: "v2>vA33de0dTejshriBhagwa"
                  user: "CEUSER"
                - group: "netedit"
                  password: "kyfF8[XWc18"
                  user: "ISFUSER"
                - group: "netedit"
                  password: "Abell4Cloud!"
                  user: "cumulus"

