
- name: Set vault credentials
  set_fact:
    vault_response:
      status: "Success"
      message: "Vault credentials retrieved successfully."
      messageCode: "INSTALL042"
      messageArgs: null
      errorMessage: ""
      data:
        CNIMMSecret:
          CNIMMSecret:
            - name: "control-1-ru2-secret"
              users:
                - group: "Administrator"
                  password: "dl9GajRHRVlVRVE="
                  user: "CEUSER"
                - group: "Administrator"
                  password: "YjBvbTR6X1VoV0s="
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "YWhLWEdUcG9jMw=="
                  user: "USERID"
            - name: "control-1-ru3-secret"
              users:
                - group: "Administrator"
                  password: "dURmTmIzN0hackA="
                  user: "CEUSER"
                - group: "Administrator"
                  password: "UUkyaTBAUElBTDA="
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "YWhLWEdUcG9jMw=="
                  user: "USERID"
            - name: "control-1-ru4-secret"
              users:
                - group: "Administrator"
                  password: "c0k4WkZlVDRWX2k="
                  user: "CEUSER"
                - group: "Administrator"
                  password: "R0pkaHdtNWM5LWk="
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "YWhLWEdUcG9jMw=="
                  user: "USERID"
            - name: "compute-1-ru5-secret"
              users:
                - group: "Administrator"
                  password: "QjY4N05QYUJnLTE="
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "SlVoV1RpUTlsNw=="
                  user: "USERID"
                - group: "Administrator"
                  password: "ejBRdWp5aDFoNl8="
                  user: "CEUSER"
            - name: "compute-1-ru6-secret"
              users:
                - group: "Administrator"
                  password: "aEpTc202OFVxXzE="
                  user: "CEUSER"
                - group: "Administrator"
                  password: "Y0dpQFpHRzk2NmU="
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "MkV4U2pKb3pxOQ=="
                  user: "USERID"
            - name: "compute-1-ru7-secret"
              users:
                - group: "Administrator"
                  password: "VUB0aTNvNmJaaGE="
                  user: "ISFUSER"
                - group: "Administrator"
                  password: "NTU5dml2WTBTNg=="
                  user: "USERID"
                - group: "Administrator"
                  password: "dkE0X3A1UGZrcGg="
                  user: "CEUSER"
            - name: "servicenode-1-secret"
              users:
                - group: "Administrator"
                  password: "PASSW0RD"
                  user: "USERID"
                - group: "Administrator"
                  password: "CYRqU4#8lPqTejshr"
                  user: "CEUSER"
                - group: "Administrator"
                  password: "aaj530H3r@3"
                  user: "ISFUSER"
        ProvisionerPubPrivKeySecret:
          ProvisionerPubPrivKeySecret:
            - privateKey: |
                -----BEGIN OPENSSH PRIVATE KEY-----
                b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
                c2gtZWQyNTUxOQAAACBYdBB/WDQbZDwPUEwk00/zjkEPR5yfnPubgdX3tz7kIQAA
                AIhrHnpvax56bwAAAAtzc2gtZWQyNTUxOQAAACBYdBB/WDQbZDwPUEwk00/zjkEP
                R5yfnPubgdX3tz7kIQAAAEDSGO42NWO7VlCqXq35CO3umNi09RGCqi9D6feWPKCK
                Vlh0EH9YNBtkPA9QTCTTT/OOQQ9HnJ+c+5uB1fe3PuQhAAAAAAECAwQF
                -----END OPENSSH PRIVATE KEY-----
              publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFh0EH9YNBtkPA9QTCTTT/OOQQ9HnJ+c+5uB1fe3PuQh\n"
        SwitchSecret:
          SwitchSecret:
            - name: "hspeed1-f24l026-secret"
              snmpAuthPassword: "VsZbt3Nh89Tejsh"
              snmpPrivPassword: "kdLMuC237y"
              snmpUser: "ISFSNMPUSR"
              users:
                - group: "netedit"
                  password: "MF9Rem9IVTMzU2s="
                  user: "CEUSER"
                - group: "netedit"
                  password: "WmxiczN2Y0wyLVU="
                  user: "ISFUSER"
                - group: "admin"
                  password: "Abell4Cloud!"
                  user: "cumulus"
            - name: "hspeed2-f24l026-secret"
              snmpAuthPassword: "qD4fEpz71mTejshri"
              snmpPrivPassword: "3V4H2fmnlk"
              snmpUser: "ISFSNMPUSR"
              users:
                - group: "netedit"
                  password: "QTB1QlBteV81YjI="
                  user: "CEUSER"
                - group: "netedit"
                  password: "SzVPWGJQYkhfeE0="
                  user: "ISFUSER"
                - group: "admin"
                  password: "Abell4Cloud!"
                  user: "cumulus"
            - name: "mgmt1-f24l026"
              snmpAuthPassword: "0Pi2jEBYQ9Tejshri"
              snmpPrivPassword: "Yhv4n5FTS2"
              snmpUser: "ISFSNMPUSR"
              users:
                - group: "netedit"
                  password: "aHE0dVZAdnVCMTI="
                  user: "CEUSER"
                - group: "netedit"
                  password: "OTlVUXhIel85NU8="
                  user: "ISFUSER"
                - group: "netedit"
                  password: "QWJlbGw0Q2xvdWQh"
                  user: "cumulus"
            - name: "mgmt2-f24l026"
              snmpAuthPassword: "f5es9xQMj3fusioninstallTejshri"
              snmpPrivPassword: "N60cR9ruIa"
              snmpUser: "ISFSNMPUSR"
              users:
                - group: "netedit"
                  password: "ZDY0QzBfRENMY3A="
                  user: "CEUSER"
                - group: "netedit"
                  password: "QzZEbFBXNEBXWkE="
                  user: "ISFUSER"
                - group: "netedit"
                  password: "QWJlbGw0Q2xvdWQh"
                  user: "cumulus"
                  
- name: Display vault responses
  debug:
    msg: "Found {{ vault_response.data.CNIMMSecret }} compute nodes"

