
# AWX Connection
awx_host: "localhost"
awx_port: 8443
awx_user: "admin"
awx_password: "admin"
awx_scheme: "https"
validate_certs: false
awx_organization_id: 1

# IMM Credential Type
bmc_credential_type_name: "ServerCredentials"
bmc_credential_type_kind: "cloud"
bmc_default_group: "Administrator"

# Loop defaults
retrieved_cnimm: []
cnimm: []
bmc_credential_type_id: ""
bmc_paths: []
