
# AWX Connection
awx_host: "{{ awx_host | default('localhost', true) }}"
awx_port: "{{ awx_port | default(8443, true) }}"
awx_url: "http://{{ awx_host }}:{{ awx_port }}"
awx_user: "{{ awx_user | default('admin', true) }}"
awx_password: "{{ awx_password | default('admin', true) }}"
awx_organization_id: 1
validate_certs: false

# IMM Credential Type
bmc_credential_type_name: "BMC User Credentials"
bmc_credential_type_kind: "cloud"
bmc_default_group: "Administrator"

# Loop defaults
retrieved_cnimm: []
cnimm: []
bmc_credential_type_id: ""
bmc_paths: []
