
# AWX Connection
awx_host: "{{ lookup('env', 'AWX_HOST') | default('localhost', true) }}"
awx_port: "{{ lookup('env', 'AWX_PORT') | default(8443, true) }}"
awx_url: "https://{{ awx_host }}:{{ awx_port }}"
awx_user: "{{ lookup('env', 'AWX_USER') | default('admin', true) }}"
awx_password: "{{ lookup('env', 'AWX_PASSWORD') | default('admin', true) }}"
awx_organization_id: 1
validate_certs: false

# IMM Credential Type
bmc_credential_type_name: "BMC User Credentials"
bmc_credential_type_kind: "cloud"
bmc_default_group: "Administrator"

# Loop defaults
retrieved_cnimm: []
bmc_credential_type_id: ""
bmc_paths: []
