---

- name: Ensure chrony is installed
  package:
    name: "{{ time_sync_chrony_package }}"
    state: present
  become: yes

- name: Backup existing chrony configuration
  copy:
    src: "{{ time_sync_chrony_config }}"
    dest: "{{ time_sync_chrony_config }}.backup"
    remote_src: yes
  become: yes
  failed_when: false
  when: time_sync_backup_config | bool
